### ISSUE TITLE
403 or 401?

### ISSUE THREAD

**Issue by elgris** [seesawlabs/ivan-kirichenko-exercise#1]
A question about #2

```
Implement login endpoint with JWT token, and simple middleware that checks header for 'Authorization: Bearer %jwt_token%' in each request. Otherwise return 403 and json struct with error
```

I suppose to use `401` HTTP code here, because it stands for `Unauthorized` which means "invalid access token". Response code `403` stands for `Forbidden`. I'd return it if user comes with correct JWT token, but has no privilege to access some resource.

**Comment by eolexe** [comment]
Agreed
